/*
 * Generated Code for com.objectfrontier.rtgs.msg.defn.MsgFieldFormat
 * Please do not alter the code.
 *
 * @date     10-15-08
 */

package com.objectfrontier.rtgs.msg.defn.client.vo;


import java.io.Serializable;
/**
 * 
 *
 * @class    com.objectfrontier.rtgs.msg.defn.client.vo.MsgFieldFormatValueObject.java
 * @see      
 * @date     10-15-08
 */


public class MsgFieldFormatValueObject implements Serializable { 

	public long id;
	public int length;
	public int minLength;
	public boolean fixedLength;
	public int lineCount;
	public int minLineCount;
	public java.lang.String padding;
	public java.lang.String expression;
	public java.lang.String displayType;
	public java.lang.String justification;
	public boolean isAutoGenerated;
	public long ObjectTimestamp;


	/**
	 * Get value of attribute - id
	 *
	 * @return id
	 */
	public long getId(){
		return this.id;
	}


	/**
	 * Get value of attribute - length
	 *
	 * @return length
	 */
	public int getLength(){
		return this.length;
	}


	/**
	 * Get value of attribute - minLength
	 *
	 * @return minLength
	 */
	public int getMinLength(){
		return this.minLength;
	}


	/**
	 * Get value of attribute - fixedLength
	 *
	 * @return fixedLength
	 */
	public boolean getFixedLength(){
		return this.fixedLength;
	}


	/**
	 * Get value of attribute - lineCount
	 *
	 * @return lineCount
	 */
	public int getLineCount(){
		return this.lineCount;
	}


	/**
	 * Get value of attribute - minLineCount
	 *
	 * @return minLineCount
	 */
	public int getMinLineCount(){
		return this.minLineCount;
	}


	/**
	 * Get value of attribute - padding
	 *
	 * @return padding
	 */
	public java.lang.String getPadding(){
		return this.padding;
	}


	/**
	 * Get value of attribute - expression
	 *
	 * @return expression
	 */
	public java.lang.String getExpression(){
		return this.expression;
	}


	/**
	 * Get value of attribute - displayType
	 *
	 * @return displayType
	 */
	public java.lang.String getDisplayType(){
		return this.displayType;
	}


	/**
	 * Get value of attribute - justification
	 *
	 * @return justification
	 */
	public java.lang.String getJustification(){
		return this.justification;
	}


	/**
	 * Get value of attribute - isAutoGenerated
	 *
	 * @return isAutoGenerated
	 */
	public boolean getIsAutoGenerated(){
		return this.isAutoGenerated;
	}


	/**
	 * Get value of attribute - ObjectTimestamp
	 *
	 * @return ObjectTimestamp
	 */
	public long getObjectTimestamp(){
		return this.ObjectTimestamp;
	}


	/**
	 * Set value of attribute - id
	 *
	 * @param id
	 */
	public void setId(long id){

		this.id = id;
	}


	/**
	 * Set value of attribute - length
	 *
	 * @param length
	 */
	public void setLength(int length){

		this.length = length;
	}


	/**
	 * Set value of attribute - minLength
	 *
	 * @param minLength
	 */
	public void setMinLength(int minLength){

		this.minLength = minLength;
	}


	/**
	 * Set value of attribute - fixedLength
	 *
	 * @param fixedLength
	 */
	public void setFixedLength(boolean fixedLength){

		this.fixedLength = fixedLength;
	}


	/**
	 * Set value of attribute - lineCount
	 *
	 * @param lineCount
	 */
	public void setLineCount(int lineCount){

		this.lineCount = lineCount;
	}


	/**
	 * Set value of attribute - minLineCount
	 *
	 * @param minLineCount
	 */
	public void setMinLineCount(int minLineCount){

		this.minLineCount = minLineCount;
	}


	/**
	 * Set value of attribute - padding
	 *
	 * @param padding
	 */
	public void setPadding(java.lang.String padding){

		this.padding = padding;
	}


	/**
	 * Set value of attribute - expression
	 *
	 * @param expression
	 */
	public void setExpression(java.lang.String expression){

		this.expression = expression;
	}


	/**
	 * Set value of attribute - displayType
	 *
	 * @param displayType
	 */
	public void setDisplayType(java.lang.String displayType){

		this.displayType = displayType;
	}


	/**
	 * Set value of attribute - justification
	 *
	 * @param justification
	 */
	public void setJustification(java.lang.String justification){

		this.justification = justification;
	}


	/**
	 * Set value of attribute - isAutoGenerated
	 *
	 * @param isAutoGenerated
	 */
	public void setIsAutoGenerated(boolean isAutoGenerated){

		this.isAutoGenerated = isAutoGenerated;
	}


	//Enterprise Rules Start Here





	//Enterprise Rules End Here

}
