/*
 * @(#)RHSConstants.java
 *
 * Copyright by ObjectFrontier, Inc.,
 * 12225 Broadleaf Lane, Alpharetta, GA 30005, U.S.A.
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of ObjectFrontier, Inc. You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of
 * the license agreement you entered into with ObjectFrontier.
 */
package com.objectfrontier.insta.reports.server.util;

/**
 * @author johne;Sep 3, 2004
 * @date   Sep 3, 2004
 * @since  RHS APP 1.0; Sep 3, 2004
 * @see    
 */
public interface RHSConstants 
extends com.objectfrontier.rtgs.util.Constants {

//    String DEFAULT_USER = "9016";
    
    String DEFAULT_USER = "system";
        
    // following constants added for supporting the message definition client 
    String JUSTIFY_LEFT = "left";
    String JUSTIFY_RIGHT = "right";
    String PADDING_CHAR = "0";
    String NEW_LINE_STRING_EMPTY = "";
    String NEW_LINE_STRING = "\\r\\n";
    
    //Swift messsage 
    String SWIFT_NEW_LINE_STRING = "\r";
    String SWIFT_FIELD_END_DELIMITER = "\r";
     
    String FIELD_START_DELIMITER = "/";
    String FIELD_END_DELIMITER = "\\r\\n";
    
    String FIELD_MULTILINE_START_DELIMITER = "//";
    String ALTERNATE_FIELD_END_DELIMITER = "\\n";
    
    //swift message
    String SWIFT_ALTERNATE_FIELD_END_DELIMITER = "\r";
    
    String COMPOUND_FIELD_DELIMITER = NEW_LINE_STRING;
    String FIELD_DELIMITER_EMPTY = "";
    String DEFAULT_VALUE_EMPTY = ""; 
    boolean FIXEDLENGTH_TRUE = true ;
    boolean FIXEDLENGTH_FALSE = false;
    boolean VARIABLELENGTH_TRUE = true ;
    boolean VARIABLELENGTH_FALSE = false;
    boolean CONSTANT_TRUE = true ;
    boolean CONSTANT_FALSE = false;
    boolean MANDATORY_TRUE = true ;
    boolean MANDATORY_FALSE = false;
    boolean MULTILINE_TRUE = true;
    boolean MULTILINE_FALSE = false;
    boolean USEQUALIFIEDFIELD_TRUE = true;
    boolean USEQUALIFIEDFIELD_FALSE = false;
    boolean AUTOGENERATED_TRUE = true;
    boolean AUTOGENERATED_FALSE = false;
    boolean REQUIRESNEXTFIELDSD_TRUE = true;
    boolean REQUIRESNEXTFIELDSD_FALSE = false;
    
    String BLOCK_SIMPLE = "simple";
    String BLOCK_GROUP = "group";
    String DATATYPE_STRING = "String";
    String DATATYPE_ALPHABETIC = "alphabetic";
    String DATATYPE_ALPHANUMERIC = "alphanumeric";
    String DATATYPE_NUMERIC = "numeric";
    String DATATYPE_CHAR = "char";
    String DATATYPE_DATE = "date";
    String DATATYPE_AMOUNT = "amount";
    String DATATYPE_MONEY = "money";
    
    String IOBIFSC_QUERY = "select ifsc as Ifsc, name as Name,address as Address from com.host.rhs.meta.HostIFSCDetails";
    String IOBIFSC_FIELDNAME = "ifsc";
    String IOBIFSC_DISPLAYNAME = "name";
    String IFSC_QUERY = "select ifsc as Ifsc, name as Name,address as Address from com.objectfrontier.rhs.meta.IFSCMaster";
    String IFSC_FIELDNAME = "ifsc";
    String IFSC_DISPLAYNAME = "name";
    String USER_DEFINED_QUERY = "select code,desc from com.objectfrontier.rhs.meta.ReasonCode where type = 'userdefined'";
    String USER_DEFINED_FIELDNAME = "code";
    String USER_DEFINED_DISPLAYNAME = "desc";
    String CREDIT_DEBIT_QUERY = "select code,desc from com.objectfrontier.rhs.meta.ReasonCode where type = 'creditdebit'";
    String CREDIT_DEBIT_FIELDNAME = "code";
    String CREDIT_DEBIT_DISPLAYNAME = "desc";
    String REASON_QUERY = "select code,desc from com.objectfrontier.rhs.meta.ReasonCode where type = 'reason'";
    
    String MSG_DBCONNECTIONAttributes       = "MSG_011";
    
    String TRASH_QUEUE_NAME = "trash-queue-name";
    
    String BRANCH_CONNECITON_INITIATOR_TIME = "BRANCH_CONNECTION_INITIATOR_TIME";

    String PUSH_BACK_TO_WORKFLOW_TIME = "PUSH_BACK_TO_WORKFLOW_TIME";

    String INSUFFICIENT_BALANCE_TIME = "INSUFFICIENT_BALANCE_TIME";

//    String KEY_MQCONNECTION_END_TIME = "mq-connection-end-time";
//    
//    String KEY_MQCONNECTION_START_TIME = "mq-connection-start-time";

    String KEY_MQCONNECTION_INTERVAL_TIME = "MQ_CONNECTION_INTERVAL_TIME";

    String KEY_SCHEDULE_INTERVAL_TIME = "schedule-interval-time";
    
    String FUNDS_TRANSFER_BRANCH = "FUNDS_TRANSFER_BRANCH";

    String OUTWARD_TRANSACTION_TYPE = "outward";
    
    String INWARD_TRANSACTION_TYPE = "inward";
    
    String OUT_TRANSACTION_TYPE = "O";
    
    String IN_TRANSACTION_TYPE = "I";
    
    String REASON_CODE_TYPE = "MSG-IFSC";
    
    String CO_VOUCHING_IFSC = "IFSC_CO_VOUCHING";
    
    String EMAIL_MQ_CONNECTION_FAILED = "mq-connection-failed"; 
    
    String EMAIL_INSUFFICENT_BALANCE = "insufficient-balance-exception";
    
    String EMAIL_DB_CONNECTION_FAILED = "db-connection-failed";
    
    String EMAIL_USER_ADMIN = "admin";
    
    String EMAIL_TRASH_QUEUE = "trash-queue";
    
    String EMAIL_TIMEOUT_TASK = "time-out";
    
    String EMAIL_IFSC_MASTER = "ifsc-master";
    
    String EMAIL_INVALID_IFSC_MASTER = "invalid-ifsc-master";
    
    String EMAIL_DEFAULT = "global";
    
    String TBA = "TBA";
    String TRIMS = "TRIMS";
    String Default = "Default";

    String[] BranchTypeNames = {TBA, Default};

    String BOTH_TRANSACTION_TYPE = "both";

    String KEY_MESSAGE_TYPE     = "298";
    
    String IPR_MESSAGE_TYPE = "298/R42";
    String CPR_MESSAGE_TYPE = "298/R41";
    String OATR_MESSAGE_TYPE = "298/R10";
    String NCR_MESSAGE_TYPE = "298/R12";
    String DN_MESSAGE_TYPE = "298/R43";
    
    String IPR_MESSAGE_SUB_TYPE = "R42";
    String CPR_MESSAGE_SUB_TYPE = "R41";
            
    String MESSAGE_FLAG_INTERNAL = "internal";
    String MESSAGE_FLAG_EXTERNAL = "external";
    
    String MT103_MESSAGE_TYPE = "103";
    String MT202_MESSAGE_TYPE = "202";
    
    //For RBC
    String COREIFSC         = "COREIFSC";
    
    String DEBITACCNO           = "DEBITACCNO";
    String SOL                  = "SOL";
    String DEBITREMARKS         = "DEBITREMARKS";
    String FILE_SRC_PATH        = "FILE_SRC_PATH";
    String FILE_DEST_PATH       = "FILE_DEST_PATH";
    String FILE_BAKUP_PATH      = "FILE_BAKUP_PATH";
    String FILE_TIMEDOUT_PATH   = "FILE_TIMEDOUT_PATH";
    String FILE_PROCESSED_PATH   = "FILE_PROCESSED_PATH";
    String FILE_ERR_PATH        = "FILE_ERR_PATH";
    String IPRPOLLTIME          = "IPRPOLLTIME";
    String CPRPOLLTIME          = "CPRPOLLTIME";
    String SAT_IPRPOLLTIME          = "SAT_IPRPOLLTIME"; //Saturday IPR Poll Time
    String SAT_CPRPOLLTIME          = "SAT_CPRPOLLTIME"; //Saturday CPR Poll Time
    String FILE_EXT             = "FILE_EXT";


    String NEWLINECHAR      = "NEWLINECHAR";
    String IWFILENAME       = "IWFILENAME";
    String DR               = "D";
    String CR               = "C";
    String CURRECNY_CODE    = "INR";
    String CORE             = "CORE";
    String SEQNOLEN         = "SEQNOLEN";
    String MSG_ID           = "MSGID";
    String ACCOUNT_NUMBER   = "ACCS"; 
    String AMOUNT           = "AMTS";
    String ISSENDHOST         = "ISSENDHOST"; //23-Sep-06
    String RTGSCHRG         = "RTGSCHRG";
    String RTGSCHRGPOSTED   = "RTGCHRGPOSTED";
    
    String UPDATE           = "update";
    String INSERT           = "insert";
   
    //QUERY_PARAM is used as filters to get the CodeWords 
    String QUERY_PARAM      = "subMsgType#fieldNo#codeWord#";
    String QUERY_DELIMITER  = "#";

    //RBC CMD 1.0
    String IPRTHRESHOLD = "IPRTHRESHOLD";
    String CPRTHRESHOLD = "CPRTHRESHOLD";
    String IDL       = "IDL";
    String BRANCH_TREASUARY = "TREASURY"; 
    String DEFAULT_PWD  =   ".";
    String PWD_EXPIRY_DAYS = "PWD_EXPIRY_DAYS";
    String CBS_IPR_BodyBlock = "CBS IPR BodyBlock";
    String CBS_CPR_BodyBlock = "CBS CPR BodyBlock";
    //For Outward Message C7495 Repair
    String C7495_DEFAULT    = "C7495_DEFAULT";
    String IPR_C7495_DEFAULT    = "IPR_C7495_DEFAULT";
    String CPR_C7495_DEFAULT    = "CPR_C7495_DEFAULT";
    String DELIMITER    = "DELIMITER";
    String SLASH        = "SLASH";  
    String C7495_MAXLEN = "C7495_MAXLEN";
    //For Inward Message change
    String INWARD_ROW_LEN   = "INWARD_ROW_LEN";           
    String INSTRUMENT_TYPE   = "INSTRUMENT_TYPE";
    String INWARD_REMARKS   = "INWARD_REMARKS";
    String itSIndex     = "itSIndex";
    String itEIndex     = "itEIndex";
    String vdSIndex     = "vdSIndex";
    String vdEIndex     = "vdEIndex";
    String remSIndex    = "remSIndex";
    String remEIndex    = "remEIndex";
    String remLen        = "remLen";
    String itLen        = "itLen";
    String vdLen        = "vdLen";
    String BLOCK_END_IDENTIFIER = "-}";
    String EOB           = "EOB";
    String EOF           = "EOF";
    String SOM           = "SOM";
    String SOB           = "SOB";
    String SOF           = "SOF";
    
    String RTGS_CHANNEL = "RTGS";
    String BACS_CHANNEL = "BACS";

    String CBSServer       = "CBSServer";     
    String CBSServerPortNo = "CBSServerPortNo";
    String BackLog = "BackLog";
    String ISO_KEY_MESSAGE_TYPE     = "0";
    String ISO_KEY_MESSAGE_SUBTYPE  = "1200";
    String BANKID = "BANKID";
    String BANKIDLEN = "BANKIDLEN";
    String SOLIDLEN = "SOLIDLEN";
    String ACCNOLEN = "ACCNOLEN";
    String ISOFIELD103_CHARCODE = "ISOFIELD103_CHARCODE";
    String ConnectWithCBS = "ConnectWithCBS";
    
    String RTGSCHRGS_CR_ACCNO = "RTGSCHRGS_CR_ACCNO";
    
    //Financial Transaction has been approved in Bancsconnect
    String HOST_FIN_TXN_APPROVED_CODE = "000"; 
    //ISO Invalid account number Code
    String HOST_INVALID_ACC_NO_CODE = "114";
    
    String RTG_KEY_SSN_SUBTYPE = "R09";
    String RTG_SETTL_VAL = "Y";   
    String ISOMSG = "ISOMSG";
    String MSGDTO = "MSGDTO";
    
    //For Testing only
    String SendRequestToCBS = "SendRequestToCBS";
    String GetResponseFromCBS = "GetResponseFromCBS";
    String ApplyRTGSCHRGResponse = "ApplyRTGSCHRGResponse";
    String SendRTGSCHRGSRequestToCBS = "SendRTGSCHRGSRequestToCBS";
    String RTGSCHARGE = "RTGSCHARGE";
    String RTGSCHRG_FLAT = "Flat";
    String RTGSCHRG_PERCENT = "Percent";
    String RTGSCHRG_DEFAULT = "DEFAULT";
    String NRIACCOUNT_IDENTIFIER    = "NRIACCOUNT_IDENTIFIER";
    String REQUEST  =   "REQ";
    String RESPONSE =   "RES";
    String ASCII_REPLACE = "XXXXXXXXXXXXXXXX";
    String BOR_ACCN0_MIN_LEN = "BOR_ACCN0_MIN_LEN";       
    String SYSTEM = "system";

    String FILE_DUPLICATED_PATH = "FILE_DUPLICATED_PATH";
    // For Neft Outward Summary Report
    int OUTWARD_COMPLETE_STATUS = 3000;
    int REJECTED_BY_RBI_STATUS = 2900;
    int RESCHEDULED_BY_RBI_STATUS = 2550;
    
}

